replicaCount: 1

image:
  repository: ollama/ollama
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 11434

ingress:
  enabled: true
  className: nginx
  host: ollama.jamorgado.es
  tls: false

resources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "1"
    memory: "2Gi"

persistence:
  enabled: true
  size: 10Gi